Repository The-Merchants-Guild/Merchant-Station-13, pull requests merged in 2022-05, with the labels that each got.

#167 Re-adds pitch black spraycans.
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/crayons.dm
  code/game/objects/structures/window.dm
Labels: Tweak

#194 Makes the minimum required players for all deathmatch maps 2
  code/modules/deathmatch/deathmatch_maps.dm
Labels: ✔️ Wedditor, Tweak

#212 Fix the discord button for dark theme
  tgui/packages/tgui-panel/themes.js
Labels: Fix

#200 Makes Null_crates cheaper by a factor of three
  code/modules/cargo/packs.dm
Labels: Tweak

#219 Fixes automatic viewport fitting
  code/datums/view.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/ooc.dm
Labels: Fix

#221 Clean up deathmatch player mind properly.
  code/modules/deathmatch/deathmatch_lobby.dm
Labels: Fix, ✔️ Wedditor

#226 SNEED VENDORS WHOO!!!!!
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/modules/economy/point_vendors/hydroponics.dm
  code/modules/vending/megaseed.dm
  tgstation.dme
Labels: Feature, Mapping

#203 Mentors ported from Fulpstation
  SQL/admin_import_2018-02-03.py
  SQL/database_changelog.txt
  SQL/tgstation_schema.sql
  SQL/tgstation_schema_prefixed.sql
  code/__DEFINES/admin.dm
  code/__DEFINES/keybinding.dm
  code/__DEFINES/subsystems.dm
  code/controllers/configuration/entries/general.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/verbs/admin.dm
  code/modules/admin/verbs/admingame.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/mentorhelp/ahelp_reject.dm
  code/modules/mentorhelp/follow.dm
  code/modules/mentorhelp/mentor.dm
  code/modules/mentorhelp/mentor_clientprocs.dm
  code/modules/mentorhelp/mentor_globalvars.dm
  code/modules/mentorhelp/mentor_keybinds.dm
  code/modules/mentorhelp/mentor_logging.dm
  code/modules/mentorhelp/mentorhelp.dm
  code/modules/mentorhelp/mentorpm.dm
  code/modules/mentorhelp/mentorsay.dm
  code/modules/mentorhelp/mentorwho.dm
  config/config.txt
  config/mentors.txt
  tgstation.dme
Labels: Feature, TEST MERGE
