Repository The-Merchants-Guild/Merchant-Station-13, pull requests merged in 2022-06, with the labels that each got.

#245 Fix CI Linter Errors
  .github/workflows/ci_suite.yml
Labels: Fix, ✔️ Wedditor

#243 Add plastic pots
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/hydroponics/hydroponics.dm
  icons/obj/flora/plants.dmi
Labels: Feature

#173 Speech filtration implants pt. 2: coding boogaloo
  code/__DEFINES/DNA.dm
  code/__DEFINES/logging.dm
  code/__HELPERS/_logging.dm
  code/controllers/configuration/entries/general.dm
  code/game/atoms.dm
  code/modules/modular_computers/file_system/programs/wbcontroller.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/cybernetics/augments_internal_wordblock.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/NtosImplantController.js
Labels: Feature, ✔️ Wedditor

#258 Revert "Makes Null_crates cheaper by a factor of three"
  code/modules/cargo/packs.dm
Labels: To be defenestrated, Tweak

#259 Fix point vendors
  code/modules/vending/point_vendor.dm
  code/modules/vending/point_vendors/engineering.dm
  code/modules/vending/point_vendors/hydroponics.dm
  code/modules/vending/point_vendors/medical.dm
  code/modules/vending/point_vendors/security.dm
  tgstation.dme
Labels: Fix, HOLY FUCK

#257 Fixes escaping the DM(I hope)
  _maps/map_files/DM/Maint_Mania.dmm
  _maps/map_files/DM/OSHA_Violator.dmm
Labels: Fix, To be defenestrated

#256 Adds surplus crate-only items.
  code/game/objects/items/plushes.dm
  code/modules/uplink/surplus_items.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/clothing/feet.dmi
  icons/mob/inhands/equipment/custodial_lefthand.dmi
  icons/mob/inhands/equipment/custodial_righthand.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/guns/ballistic.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/janitor.dmi
  sound/misc/lubricator.ogg
  sound/weapons/blood_debt.ogg
  tgstation.dme
Labels: Feature

#252 Adds the supermatter spear.
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/spear.dm
  icons/mob/inhands/weapons/polearms_lefthand.dmi
  icons/mob/inhands/weapons/polearms_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Feature, HOLY FUCK

#255 SLIPS HARDSTUN AGAIN
  code/datums/materials/basemats.dm
  code/game/objects/effects/decals/cleanable/robots.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/food/bread.dm
  code/game/objects/items/food/meat.dm
  code/modules/antagonists/clown_ops/clown_weapons.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/hydroponics/plant_genes.dm
Labels: Readds fun, Tweak

#262 A few small chem fixes
  code/game/objects/items/grenades/chem_grenade.dm
  code/modules/reagents/chemistry/recipes.dm
Labels: Fix, Tweak

#237 TGUI-based ERT spawning menu + Custom ERTs
  code/datums/ert.dm
  code/modules/admin/verbs/ert.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/jobs/card_accesses/centcom.dm
  tgui/packages/tgui/interfaces/ErtMaker.tsx
Labels: Feature, Work In Progress

#230 Tesla explodes again
  code/__DEFINES/flags.dm
  code/modules/power/tesla/energy_ball.dm
Labels: Readds fun, TEST MERGE

#239 You can use self surgery on head again
  code/modules/surgery/surgery_step.dm
Labels: Readds fun, TEST MERGE, Tweak

#246 Fix Wikibooks
  code/controllers/configuration/entries/general.dm
  code/game/objects/items/manuals.dm
  config/config.txt
  interface/interface.dm
Labels: Fix, TEST MERGE

#270 Adds more HEV suit sound effects, 1/5 chance of the RD suit being in an EOD closet, changed its name, removed reagent scanner..
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  sound/effects/blood_loss.ogg
  sound/effects/major_lacerations.ogg
  sound/effects/minor_lacerations.ogg
Labels: Feature, Readds fun, Tweak

#269 Allow organ manipulation on prosthetic legs.
  code/modules/surgery/organ_manipulation.dm
Labels: Fix, Tweak

#280 ERT Fix 2: Electric Boogaloo
  code/datums/ert.dm
Labels: Fix

#249 Adds the reagent forge and assorted machines and weapons.
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__DEFINES/machines.dm
  code/__DEFINES/materials.dm
  code/datums/components/_component.dm
  code/datums/components/material_container.dm
  code/datums/forge.dm
  code/datums/materials/basemats.dm
  code/game/atoms.dm
  code/game/machinery/reagent_forge.dm
  code/game/machinery/reagent_material_manipulator.dm
  code/game/machinery/reagent_refinery.dm
  code/game/objects/items/forged_weapons.dm
  code/game/objects/items/holotool.dm
  code/game/objects/items/stacks/sheets/sheets.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/open/floor/mineral_floor.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/density.dm
  code/modules/reagents/chemistry/reagents/solid_reagents.dm
  code/modules/research/designs/reagent_forge_designs.dm
  html/changelogs/archive/2020-08.yml
  icons/mob/clothing/belt.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/3x3.dmi
  icons/obj/chemical.dmi
  icons/obj/forged_weapons.dmi
  sound/misc/bustconcrete1.ogg
  sound/misc/bustconcrete2.ogg
  sound/misc/crunch.ogg
  sound/weapons/knife.ogg
  tgstation.dme
Labels: Feature, To be defenestrated, HOLY FUCK, TEST MERGE, Mapping

#288 Anturk dmi change as separate PR
  .vscode/extensions.json
  .vscode/settings.json
Labels: Feature, Tweak

#291 Add a Code of Conduct
  CODE_OF_CONDUCT.md
Labels: Feature, ✔️ Wedditor

#293 Uplifts the limit on the cards
  code/__DEFINES/id_cards.dm
Labels: Readds fun, Tweak

#196 Adds a new sprite for the stacker
  code/modules/mining/bluespace.dm
  icons/obj/machines/mining_machines.dmi
Labels: Feature

#267 Krav Maga changes
  code/datums/martial/krav_maga.dm
Labels: Fix, Tweak

#290 Fixes the BP Grenades
  code/__HELPERS/atoms.dm
  code/datums/wires/explosive.dm
  code/game/machinery/deployable.dm
  code/game/machinery/syndicatebomb.dm
  code/game/objects/items/grenades/_grenade.dm
  code/game/objects/items/grenades/antigravity.dm
  code/game/objects/items/grenades/atmos_grenades.dm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/grenades/clusterbuster.dm
  code/game/objects/items/grenades/emgrenade.dm
  code/game/objects/items/grenades/festive.dm
  code/game/objects/items/grenades/flashbang.dm
  code/game/objects/items/grenades/ghettobomb.dm
  code/game/objects/items/grenades/hypno.dm
  code/game/objects/items/grenades/plastic.dm
  code/game/objects/items/grenades/smokebomb.dm
  code/game/objects/items/grenades/syndieminibomb.dm
  code/modules/antagonists/clown_ops/clown_weapons.dm
  code/modules/aquarium/aquarium.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/ninja/ninja_explosive.dm
  code/modules/reagents/chem_splash.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/experimentor.dm
  tgstation.dme
Labels: Fix, TEST MERGE

#304 Wet floor slips ALSO stun you, and if you go into another lube tile once lubed already, you go forward more
  code/datums/components/wet_floor.dm
  code/game/turfs/open/_open.dm
Labels: Feature, Readds fun, Tweak

#303 [Port From Paradise Station] Syndicate Teleporter
  code/game/objects/items/teleportation.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#305 Farts spawn miasma.
  code/modules/hydroponics/grown/buttflower.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/vending/megaseed.dm
Labels: Feature

#302 Midround Antag - Patient Zero
  code/modules/events/patient_zero.dm
  tgstation.dme
Labels: Feature

#309 Adds a few space funeral mobs.
  code/modules/mob/living/simple_animal/hostile/retaliate/spacefuneral.dm
  icons/mob/spacefuneral.dmi
  sound/weapons/leghorse.ogg
  sound/weapons/philip.ogg
  tgstation.dme
Labels: Feature

#297 Adds an automatic kick feature for server jannies for accounts that are too new.
  code/controllers/configuration/entries/game_options.dm
  code/modules/client/misc.dm
  config/game_options.txt
  tgstation.dme
Labels: Feature

#314 Gives Engiborgs ATMOS holofan barrier projectors
  code/game/objects/items/holosign_creator.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Tweak
