Repository The-Merchants-Guild/Merchant-Station-13, pull requests merged in 2022-03, with the labels that each got.

#46 Makes items in wardrobe vending machines free for jobs in the same department.
  code/modules/vending/_vending.dm
  code/modules/vending/wardrobes.dm
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: Fix

#47 Old dynamic my beloved
  code/__DEFINES/dynamic.dm
  code/__HELPERS/roundend.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_logging.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/dynamic_simulations.dm
  code/game/gamemodes/dynamic/readme.md
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/revenant/revenant_spawn_event.dm
  code/modules/antagonists/slaughter/slaughterevent.dm
  code/modules/events/_event.dm
  code/modules/events/abductor.dm
  code/modules/events/alien_infestation.dm
  code/modules/events/blob.dm
  code/modules/events/nightmare.dm
  code/modules/events/operative.dm
  code/modules/events/pirates.dm
  code/modules/events/space_dragon.dm
  code/modules/events/space_ninja.dm
  code/modules/events/spider_infestation.dm
  code/modules/events/swarmer.dm
  code/modules/mob/mob_defines.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/dynamic_ruleset_sanity.dm
  config/dynamic.json
  tgstation.dme
Labels: Readds fun

#45 removes tram
  _maps/_basemap.dm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/tramstation.json
Labels: Fix, Removal

#53 This Kills the Manuel Bot
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/restaurant.dm
  code/datums/ai/robot_customer/robot_customer_behaviors.dm
  code/datums/ai/robot_customer/robot_customer_controller.dm
  code/datums/elements/food/venue_price.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/food/_food.dm
  code/modules/clothing/clothing.dm
  code/modules/food_and_drinks/restaurant/_venue.dm
  code/modules/food_and_drinks/restaurant/customers/_customer.dm
  code/modules/food_and_drinks/restaurant/generic_venues.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/mob/living/simple_animal/friendly/robot_customer.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/tourists.dmi
  sound/creatures/tourist/tourist_talk.ogg
  sound/creatures/tourist/tourist_talk_british.ogg
  sound/creatures/tourist/tourist_talk_french.ogg
  sound/creatures/tourist/tourist_talk_japanese1.ogg
  sound/creatures/tourist/tourist_talk_japanese2.ogg
  sound/creatures/tourist/tourist_talk_mexican.ogg
  sound/creatures/tourist/tourist_talk_moth.ogg
  tgstation.dme
Labels: Removal

#67 makes voice grenades instant again
  code/datums/wires/explosive.dm
  code/modules/assembly/voice.dm
Labels: Readds fun

#76 Xray, forum to discord, superfart in crit, thermals revert, e-gun no longer bulky
  code/controllers/configuration/entries/general.dm
  code/datums/mutations/_combined.dm
  code/datums/mutations/sight.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/research/designs/bluespace_designs.dm
  interface/interface.dm
  interface/skin.dmf
Labels: Feature, Fix, Readds fun, Removal, Tweak

#74 fix mining IDs
  code/game/objects/items/card_access_chips.dm
  code/game/objects/items/cards_ids.dm
  code/modules/mining/machine_vending.dm
Labels: Fix

#75 Fix deathmatch start being spammable.
  code/modules/deathmatch/deathmatch_lobby.dm
Labels: Fix

#1 BANG (bang assembly)
  code/modules/assembly/assembly.dm
  code/modules/assembly/bang.dm
  icons/obj/assemblies/new_assemblies.dmi
  sound/weapons/effects/bang.ogg
  tgstation.dme
Labels: Feature

#78 fix emitter icon_state not updating correctly when out of power.
  code/modules/power/singularity/emitter.dm
Labels: Fix
