Repository The-Merchants-Guild/Merchant-Station-13, pull requests merged in 2022-04, with the labels that each got.

#91 Support for hard server restart
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/ticker.dm
  code/game/world.dm
  code/modules/admin/verbs/server.dm
Labels: Feature

#95 Fixes Laser arm cybernetics containing wrong protocols, and bundles it together with a syndicate cyberlink
  code/game/objects/items/storage/briefcase.dm
  code/modules/surgery/organs/cybernetics/augments_arms.dm
  code/modules/uplink/uplink_items.dm
Labels: Fix

#94 Adds Kevlar
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/armor.dm
  code/modules/reagents/chemistry/recipes/others.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/stack_objects.dmi
Labels: Feature

#96 Fix some ID rework issues.
  code/__DEFINES/access.dm
  code/controllers/subsystem/id_access.dm
  code/game/machinery/PDApainter.dm
  code/game/machinery/doors/airlock_electronics.dm
  code/game/objects/items/cards_ids.dm
  code/modules/modular_computers/file_system/programs/card.dm
  tgui/packages/tgui/interfaces/AirlockElectronics.js
  tgui/packages/tgui/interfaces/NtosCard.js
Labels: Fix

#97 Fixes non-combat mechs not doing damage.
  code/modules/vehicles/mecha/_mecha.dm
Labels: Fix, Tweak

#107 Fixes robot pathfinding.
  code/__HELPERS/path.dm
  code/modules/wiremod/components/action/pathfind.dm
Labels: Fix

#109 Adds Standard Lab Coats to Sci Vendors
  code/modules/vending/wardrobes.dm
Labels: Feature

#110 Adds a suicide vest
  code/datums/components/crafting/recipes.dm
  code/game/sound.dm
  code/modules/clothing/suits/armor.dm
  sound/effects/Alah.ogg
  sound/effects/alah_grib.ogg
Labels: Feature

#115 Circuit printer inside integrated circuits
  code/__DEFINES/machines.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/wiremod/component.dm
  code/modules/wiremod/integrated_circuit.dm
  tgui/packages/tgui/interfaces/IntegratedCircuit/index.js
Labels: Tweak

#114 Adds the finnish quirk which gives you the spurdo mask, the alternative_screams var for items giving you different screams, and the wrestling kit for syndies.
  code/__DEFINES/traits.dm
  code/datums/martial/wrestling.dm
  code/datums/quirks/neutral.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/spurdo.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/reindex_screams.dm
  code/modules/mob/living/living_defines.dm
  code/modules/sports/wrestling.dm
  code/modules/uplink/uplink_items.dm
  icons/hud/actions.dmi
  icons/mob/clothing/eyes.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/under/syndicate.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/under/syndicate.dmi
  sound/voice/finnish_1.ogg
  sound/voice/finnish_2.ogg
  sound/voice/finnish_3.ogg
  strings/word_replacement.json
  tgstation.dme
Labels: Feature

#116 Monkey Accessible Mechs (ash walkers too)
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/vehicles/mecha/_mecha.dm
Labels: Tweak

#123 Adds the BANG assembly to autolathe.
  code/modules/research/designs/autolathe_designs.dm
Labels: Tweak

#118 Adds the HF Blade, removes the unused one from the code
  code/controllers/subsystem/traumas.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/melee/hf.dm
  code/game/objects/items/weaponry.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/hfblade.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/hfblade.dmi
  sound/weapons/hfblade-music1.ogg
  sound/weapons/hfblade-music2.ogg
  tgstation.dme
Labels: Feature

#117 Adds Armstrong Style as a martial art and syndie kit.
  code/__DEFINES/traits.dm
  code/datums/martial/armstrong_style.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/uplink/uplink_items.dm
  icons/hud/actions.dmi
  sound/misc/oof.ogg
  sound/weapons/armstrong_combo.ogg
  sound/weapons/armstrong_headbutt.ogg
  sound/weapons/armstrong_horse.ogg
  sound/weapons/armstrong_newcombo.ogg
  sound/weapons/armstrong_palmthrust.ogg
  sound/weapons/armstrong_punch.ogg
  sound/weapons/armstrong_success.ogg
  sound/weapons/armstrong_zipper.ogg
  tgstation.dme
Labels: Feature

#128 Sanitize circuits speech component
  code/modules/wiremod/components/action/speech.dm
Labels: Fix

#126 Actually allows admins to hard restart the serber
  code/modules/admin/verbs/server.dm
Labels: Fix

#127 Fix layer manifold connections
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/modules/mapping/mapping_helpers.dm
Labels: Fix, Mapping

#129 spin and flip are fun again
  code/modules/mob/emote.dm
Labels: Readds fun, Removal

#120 Makes the Savannah Ivanov MMI compatible again.
  code/__DEFINES/mecha.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/honker.dm
  code/modules/vehicles/mecha/combat/marauder.dm
  code/modules/vehicles/mecha/combat/reticence.dm
  code/modules/vehicles/mecha/combat/savannah_ivanov.dm
  code/modules/vehicles/mecha/working/clarke.dm
Labels: Tweak

#136 Fixes ghost bobbing.
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#125 Atmos traitor item :)
  code/game/objects/items/canister_regulator_breaker.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/items_and_weapons.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/Canister.js
Labels: Feature

#124 Remove tiered canisters + make plasma canister a bit more orange.
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  code/game/machinery/canister_frame.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  icons/obj/atmospherics/canisters.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/Canister.js
Labels: Readds fun, Removal, Tweak, Mapping

#121 Makes mechs explode, streamlines mech damage text alerts.
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/combat.dm
  code/modules/vehicles/mecha/combat/gygax.dm
  code/modules/vehicles/mecha/combat/marauder.dm
  code/modules/vehicles/mecha/mecha_defense.dm
  code/modules/vehicles/mecha/mecha_wreckage.dm
  sound/mecha/critical.ogg
  sound/mecha/meltdown.ogg
Labels: Feature

#105 Currently disables and partially removes purity and inverse chems
  code/__DEFINES/reagents.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/modules/reagents/chemistry/equilibrium.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/cat2_medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/impure_reagents.dm
  code/modules/reagents/chemistry/reagents/impure_reagents/impure_medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/impure_reagents/impure_toxin_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/reaction_agents_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/reagents/unique/eigenstasium.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/cat2_medicines.dm
  code/modules/reagents/chemistry/recipes/catalysts.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/chemistry/recipes/reaction_agents.dm
  tgstation.dme
Labels: Readds fun, Removal, TEST MERGE

#122 ID rework changes + fixes
  code/game/objects/items/card_access_chips.dm
  code/game/objects/items/cards_ids.dm
  code/modules/research/designs/misc_designs.dm
  icons/obj/new_id.dmi
Labels: Fix, Tweak

#119 Adds new round end sounds
  code/controllers/subsystem/ticker.dm
  sound/roundend/moon.ogg
  sound/roundend/reasonsunknown.ogg
  sound/roundend/ssethenjoyedyourchaos.ogg
  sound/roundend/ssethyoumakemesick.ogg
Labels: Feature
